Kadena-Tools
kadena-community/kadena-tools pull request #1
Opened 2021-08-05 13:30 UTC by LynxLead

Everything works, but a few things are off

- Dockerfile
I have no idea how I would have to change it, so I just didn't include it, hopefully it's not hard to add/fix
- README
Not sure if I should just copy-paste one bigger .md together, so I left it as it is right now 
- package.json
Not sure what this does in relation to the sites, so I just keep it

2021-08-05 22:01 UTC, ggobugi27 requested changes
The redesign looks great!
There are some glitches with the balance checker where the form disappears when it sees an error instead of showing the error message.
It could have to do with css changes since the form error feature was from semantic.js.
Also, please add back the url queries code - I commented below. Thanks!

2021-08-05 22:01 UTC, ggobugi27 commented on docs/balance-checker.html
> +    }, false);
Can we add the lines that were deleted from https://github.com/kadena-community/kadena-balance/blob/d1bce6b46cda5996d216bf32e64b68045bf8a421/index.html#L143
? - allows for url search.

2021-08-05 22:01 UTC, ggobugi27 commented on docs/balance-checker.html
> +            <div class="info-text">Account name is at least 3 characters</div>
Looks like this isn't rendering correctly. This message should pop up if search with wrong account length (<3, >256), but currently the entire `kadena-form` disappears with the error. 
In semantic, having this message inside the div above `ui center error message` should usually render if the class name of the form contains `error`. 
Could it be because of using local css?

2021-08-05 22:01 UTC, ggobugi27 commented on docs/balance-checker.html
> +          <div class="total-container">
This shows before the search, or when the search had an error.

2021-08-05 22:01 UTC, ggobugi27 commented on docs/balance-checker.html
> +        document.getElementById("kadena-form").className = "ui form error"
This causes the entire form to disappear, when it should render the error message.

2021-08-05 22:16 UTC, mightybyte commented
I just turned on GitHub Pages for this repo.  It's currently set to serve the `docs` folder but I can change it if there is another scheme that would be more convenient.

2021-08-06 00:47 UTC, LynxLead commented on docs/balance-checker.html
> +    }, false);
That's actually pretty odd, looks like I was using an old/wrong file, should be fixed now

2021-08-06 00:47 UTC, LynxLead commented on docs/balance-checker.html
> +            <div class="info-text">Account name is at least 3 characters</div>
Good catch, I didn't even notice that, the form shouldn't disappear anymore and about the error message, I've decided to remove the complexity from semantic and display it constantly under the input for Account name.

2021-08-13 20:09 UTC, mightybyte commented
While we're tweaking this stuff, one thing I think would be nice is if the balance checker gets the account that it is checking from the URL (i.e. `?account=alice`).  Then, when you click the "Check Balance" button it updates the URL.  That way all account balances would have links that people could paste.

2021-08-13 20:15 UTC, merged